### ISSUE TITLE
LET ME LOG IN (HE LET ME LOGIN!1!1)

### ISSUE THREAD

**Issue by PLEASELETMELOGIN** [Plagiatus/RealmsHub#1]
### Describe the bug

PLEASE LET ME LOGIN, I HAVE A MICROSOFT AND A MOJANG ACCOUNT AND ALAS I CANNOT JOIN???

**To Reproduce**
Go on Realms Hub >  click to login with microsoft > recieve error "Error during XSTS Auth." 

### Expected behavior

I am meant.... to login

### Screenshots

![Screen Shot 2022-03-16 at 8 19 57 pm](https://user-images.githubusercontent.com/101705466/158557544-7ff36dd9-1a2d-40e7-af86-8a144fcd4eba.png)

### Plattform 

_(please complete the following information if you have it)_ 

- Browser: Chrome
- Version: 99.0.4844.51
- OS: macOS
- Device: Apple Macbook

### Additional context

HELP??

**Comment by Plagiatus** [comment]
Hello and welcome to github, I see you made this account just for this bug report! 

Thank you for the report, I will investigate what might be the issue here.

**Comment by Plagiatus** [comment]
According to the logs during the estimated time of your issue, it appears that there was a 502 Error serverside. Which means that there was likely a problem with Microsofts servers at the time communicating with the realmshub servers.

Which means, the solution could be as easy as "please just try again". Also make sure to use the correct microsoft account to log in.

Please let me know whether the issue still persists.

**Comment by PLEASELETMELOGIN** [comment]
> 

I've tried another 10 times after recieving this comment and I am still not able to login via my microsoft account, I am utilising the right one, and I even tried going on the older version of the website in order to login but to avail. Please, help.

**Comment by Plagiatus** [comment]
> Please, help.

I'm trying. But sadly I'm having trouble reproducing your issue. I'll try to adapt the code in a way that should hopefully produce some better logs for me to find the problem.

Some more details as to what the error you're getting means: 

1. you're logging in with microsoft, which then allows me to get you authenticated on my server
2. your microsoft login is used to log in to the xbox live services
3. next, what _should_ happen is that that xbox live service login is used to obtain an authentication from the Xbox Secure Token Service (XSTS). but this is where the process fails in your case.

This can fail for multiple reasons, one of them being that the MS server just had a hiccup. That's why I asked you to try again a little later. If the problem persists, it has to be a systematic problem linked to YOUR account (because it cannot be reproduced with my accounts, which likely means that it's specific to your account). 

So, known issues there could be any of the following (or something else that I don't know about):

- The account doesn't have an Xbox account. Once they sign up for one (or login through minecraft.net to create one) then they can proceed with the login. This shouldn't happen with accounts that have purchased Minecraft with a Microsoft account, as they would've already gone through that Xbox signup process.  
- The account is from a country where Xbox Live is not available/banned
- The account needs adult verification on Xbox page. (South Korea)
- The account is a child (under 18) and cannot proceed unless the account is added to a Family by an adult.

Does any of this sound like it might be the issue in your case?  
The aforementioned code changes would be to determine the exact error code the XSTS returns, which could help to narrow down the error even further. But that will take a while, so if you know it could be one of the above issues you can resolve this a lot faster.

**Comment by PLEASELETMELOGIN** [comment]
> > Please, help.
> 
> I'm trying. But sadly I'm having trouble reproducing your issue. I'll try to adapt the code in a way that should hopefully produce some better logs for me to find the problem.
> 
> Some more details as to what the error you're getting means:
> 
> 1. you're logging in with microsoft, which then allows me to get you authenticated on my server
> 2. your microsoft login is used to log in to the xbox live services
> 3. next, what _should_ happen is that that xbox live service login is used to obtain an authentication from the Xbox Secure Token Service (XSTS). but this is where the process fails in your case.
> 
> This can fail for multiple reasons, one of them being that the MS server just had a hiccup. That's why I asked you to try again a little later. If the problem persists, it has to be a systematic problem linked to YOUR account (because it cannot be reproduced with my accounts, which likely means that it's specific to your account).
> 
> So, known issues there could be any of the following (or something else that I don't know about):
> 
> * The account doesn't have an Xbox account. Once they sign up for one (or login through minecraft.net to create one) then they can proceed with the login. This shouldn't happen with accounts that have purchased Minecraft with a Microsoft account, as they would've already gone through that Xbox signup process.
> * The account is from a country where Xbox Live is not available/banned
> * The account needs adult verification on Xbox page. (South Korea)
> * The account is a child (under 18) and cannot proceed unless the account is added to a Family by an adult.
> 
> Does any of this sound like it might be the issue in your case? The aforementioned code changes would be to determine the exact error code the XSTS returns, which could help to narrow down the error even further. But that will take a while, so if you know it could be one of the above issues you can resolve this a lot faster.

IVE BEEN ABLE TO LOGIN WITH YOUR HELP SIRE, THANK YOU!!! PRAISED BE YOU!1!1!1!1!


It was THE FACT I WASNT LOGGED IN TO XBOX THAT WAS THE PROBLEM!!! 

THANK YOU FOR YOUR DILIGENT RESPONSES!1!1!1

😍😍🥰🥰🥰🥰🥰😍😍😍😍😘😘😘🙃😘

**Comment by Errorcrafter** [comment]
what in the fuck

**Comment by FinnT730** [comment]
O_O

**Comment by prokube** [comment]
O_O
